server:
 port: 8888
spring:
 profiles:
  active: native
 application:
  name: config-server
 cloud:
  config:
   server:
    native:
     searchLocations: classpath:config/
eureka:
 client:
  register-with-eureka: false
  fetch-registry: false
