server:
  port: 8082
spring:
  application:
    name: movie-api
  datasource:
    hikari:
      password: root
      username: root
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    serviceUrl: [defaultZone,http://localhost:8761/eureka/]