server:
  port: 8081
spring:
  application:
    name: users-api
  datasource:
    hikari:
      password: root
      username: root
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    serviceUrl: [defaultZone,http://localhost:8761/eureka/]

